[package]
name = "ecc-rust-project"
version = "0.1.0"
edition = "2021"

[dependencies]
# num-big-int works only with 0.8.
rand = { version = "0.8.5"}
sha256 = "1.5.0"
hex = "0.4.3"
num-bigint = { version = "0.4.6" , features = ["rand"]}
